# Generated by Django 5.1.7 on 2025-04-07 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webgenda', '0002_administrador_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAdministracao',
            fields=[
                ('id_tipoatividade', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEnsino',
            fields=[
                ('id_tipoatividade', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExtensao',
            fields=[
                ('id_tipoatividade', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPesquisa',
            fields=[
                ('id_tipoatividade', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeAdministracao',
            fields=[
                ('id_atividadeadministracao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('comprovante', models.FileField(upload_to='comprovantes/')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_administracao', to='app_webgenda.docentes')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_administracao', to='app_webgenda.tipoadministracao')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeEnsino',
            fields=[
                ('id_atividadeensino', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('comprovante', models.FileField(upload_to='comprovantes/')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_ensino', to='app_webgenda.docentes')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_ensino', to='app_webgenda.tipoensino')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeExtensao',
            fields=[
                ('id_atividadeextensao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('comprovante', models.FileField(upload_to='comprovantes/')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_extensao', to='app_webgenda.docentes')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_extensao', to='app_webgenda.tipoextensao')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadePesquisa',
            fields=[
                ('id_atividadepesquisa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('comprovante', models.FileField(upload_to='comprovantes/')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_pesquisa', to='app_webgenda.docentes')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_pesquisa', to='app_webgenda.tipopesquisa')),
            ],
        ),
    ]
