# Generated by Django 5.1.7 on 2025-04-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webgenda', '0003_tipoadministracao_tipoensino_tipoextensao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeadministracao',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeensino',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeextensao',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadepesquisa',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=255),
            preserve_default=False,
        ),
    ]
