# Generated by Django 5.1.7 on 2025-09-08 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAdministracao',
            fields=[
                ('id_tipoatividade', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEnsino',
            fields=[
                ('id_tipoatividade', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExtensao',
            fields=[
                ('id_tipoatividade', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPesquisa',
            fields=[
                ('id_tipoatividade', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('aluno', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='agenda.docentes')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeAdministracao',
            fields=[
                ('id_atividadeadministracao', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('comprovante', models.FileField(upload_to='comprovantes/')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_administracao', to='agenda.docentes')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_administracao', to='agenda.tipoadministracao')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeEnsino',
            fields=[
                ('id_atividadeensino', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('comprovante', models.FileField(upload_to='comprovantes/')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_ensino', to='agenda.docentes')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_ensino', to='agenda.tipoensino')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeExtensao',
            fields=[
                ('id_atividadeextensao', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('comprovante', models.FileField(upload_to='comprovantes/')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_extensao', to='agenda.docentes')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_extensao', to='agenda.tipoextensao')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadePesquisa',
            fields=[
                ('id_atividadepesquisa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('comprovante', models.FileField(upload_to='comprovantes/')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_pesquisa', to='agenda.docentes')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_pesquisa', to='agenda.tipopesquisa')),
            ],
        ),
    ]
