# Generated by Django 5.1.7 on 2025-09-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_atividadeadministracao_comprovante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='aluno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
