@startuml WebAgenda

abstract class Atv_Docente
{
    - _id: none
    - _categoria: str
    - _nome: str
    - _data_inicio: str
    - _data_fim: str
    - _descricao: str
    - _local_curso: str
    - _periodo: str
}

class Comprovante
{
    - _nome: str
    - _data_mod: str
    - _url: str
}